Repository TarboniCar/Tarbonicar-BE, pull requests merged in 2025-06, with the labels that each got.

#6 [FEAT] 카테고리 등록, 삭제, 조회 기능 구현
  build.gradle
  src/main/java/com/tarbonicar/backend/api/category/controller/CategoryController.java
  src/main/java/com/tarbonicar/backend/api/category/dto/CarAgeResponseDTO.java
  src/main/java/com/tarbonicar/backend/api/category/dto/CarNameResponseDTO.java
  src/main/java/com/tarbonicar/backend/api/category/dto/CarTypeResponseDTO.java
  src/main/java/com/tarbonicar/backend/api/category/dto/CategoryCreateDTO.java
  src/main/java/com/tarbonicar/backend/api/category/entity/CarAge.java
  src/main/java/com/tarbonicar/backend/api/category/entity/CarName.java
  src/main/java/com/tarbonicar/backend/api/category/entity/CarType.java
  src/main/java/com/tarbonicar/backend/api/category/repository/CarAgeRepository.java
  src/main/java/com/tarbonicar/backend/api/category/repository/CarNameRepository.java
  src/main/java/com/tarbonicar/backend/api/category/repository/CarTypeRepository.java
  src/main/java/com/tarbonicar/backend/api/category/service/CategoryService.java
  src/main/java/com/tarbonicar/backend/api/health/controller/HealthCheckController.java
  src/main/java/com/tarbonicar/backend/common/config/swagger/SwaggerConfig.java
  src/main/java/com/tarbonicar/backend/common/response/ErrorStatus.java
  src/main/java/com/tarbonicar/backend/common/response/SuccessStatus.java
Labels: FEAT

#8 [FEAT] 회원가입 구현
  build.gradle
  src/main/java/com/tarbonicar/backend/api/member/controller/MemberController.java
  src/main/java/com/tarbonicar/backend/api/member/dto/MemberSignupRequestDto.java
  src/main/java/com/tarbonicar/backend/api/member/entity/Member.java
  src/main/java/com/tarbonicar/backend/api/member/repository/MemberRepository.java
  src/main/java/com/tarbonicar/backend/api/member/service/MemberService.java
  src/main/java/com/tarbonicar/backend/common/config/sescurity/SecurityConfig.java
  src/main/java/com/tarbonicar/backend/common/response/ErrorStatus.java
Labels: FEAT

#10 [FIX] Swagger Security 인증 권한 제거
  src/main/java/com/tarbonicar/backend/common/config/sescurity/SecurityConfig.java
Labels: FIX

#12 [FIX] 회원가입 Security URL 수정
  src/main/java/com/tarbonicar/backend/common/config/sescurity/SecurityConfig.java
Labels: FIX

#14 [REFAC] MemberController, Security Config 코드 정리
  src/main/java/com/tarbonicar/backend/api/member/controller/MemberController.java
  src/main/java/com/tarbonicar/backend/api/member/service/MemberService.java
  src/main/java/com/tarbonicar/backend/common/config/sescurity/SecurityConfig.java
Labels: REFAC

#16 [FEAT] 이미지 업로드 기능 구현
  build.gradle
  src/main/java/com/tarbonicar/backend/api/aws/s3/controller/S3Controller.java
  src/main/java/com/tarbonicar/backend/api/aws/s3/service/S3Service.java
  src/main/java/com/tarbonicar/backend/common/config/aws/MinioConfig.java
  src/main/java/com/tarbonicar/backend/common/config/sescurity/SecurityConfig.java
  src/main/java/com/tarbonicar/backend/common/response/ErrorStatus.java
  src/main/java/com/tarbonicar/backend/common/response/SuccessStatus.java
Labels: FEAT

#19 [FEAT] 게시글 작성, 조회, 수정, 삭제 기능 구현
  src/main/java/com/tarbonicar/backend/api/article/controller/ArticleController.java
  src/main/java/com/tarbonicar/backend/api/article/dto/ArticleCreateDTO.java
  src/main/java/com/tarbonicar/backend/api/article/dto/ArticleDetailResponseDTO.java
  src/main/java/com/tarbonicar/backend/api/article/dto/ArticleUpdateDTO.java
  src/main/java/com/tarbonicar/backend/api/article/entity/Article.java
  src/main/java/com/tarbonicar/backend/api/article/entity/ArticleLike.java
  src/main/java/com/tarbonicar/backend/api/article/entity/ArticleType.java
  src/main/java/com/tarbonicar/backend/api/article/repository/ArticleLikeRepository.java
  src/main/java/com/tarbonicar/backend/api/article/repository/ArticleRepository.java
  src/main/java/com/tarbonicar/backend/api/article/service/ArticleService.java
  src/main/java/com/tarbonicar/backend/common/config/sescurity/SecurityConfig.java
  src/main/java/com/tarbonicar/backend/common/response/ErrorStatus.java
  src/main/java/com/tarbonicar/backend/common/response/SuccessStatus.java
Labels: FEAT

#25 [FIX] 차량 연식 카테고리 조회 carName 필터 수정
  src/main/java/com/tarbonicar/backend/api/category/controller/CategoryController.java
  src/main/java/com/tarbonicar/backend/api/category/repository/CarAgeRepository.java
  src/main/java/com/tarbonicar/backend/api/category/service/CategoryService.java
  src/main/java/com/tarbonicar/backend/common/response/ErrorStatus.java
Labels: FIX

#26 [FEAT] 카카오 로그인 기능 구현
  src/main/java/com/tarbonicar/backend/api/member/controller/MemberController.java
  src/main/java/com/tarbonicar/backend/api/member/dto/KakaoUserInfoDto.java
  src/main/java/com/tarbonicar/backend/api/member/dto/MemberSignupRequestDto.java
  src/main/java/com/tarbonicar/backend/api/member/service/MemberService.java
  src/main/java/com/tarbonicar/backend/api/member/service/OAuthService.java
  src/main/java/com/tarbonicar/backend/common/config/sescurity/SecurityConfig.java
  src/main/java/com/tarbonicar/backend/common/response/ErrorStatus.java
  src/main/java/com/tarbonicar/backend/common/response/SuccessStatus.java
Labels: FEAT

#28 [FIX] 게시글 작성 시 ID 반환
  src/main/java/com/tarbonicar/backend/api/article/controller/ArticleController.java
  src/main/java/com/tarbonicar/backend/api/article/service/ArticleService.java
Labels: FIX

#31 [FEAT] 게시글 댓글 등록, 조회, 수정, 삭제 구현
  src/main/java/com/tarbonicar/backend/api/article/controller/ArticleController.java
  src/main/java/com/tarbonicar/backend/api/article/service/ArticleService.java
  src/main/java/com/tarbonicar/backend/api/comment/controller/CommentController.java
  src/main/java/com/tarbonicar/backend/api/comment/dto/CommentCreateDTO.java
  src/main/java/com/tarbonicar/backend/api/comment/dto/CommentResponseDTO.java
  src/main/java/com/tarbonicar/backend/api/comment/dto/CommentUpdateDTO.java
  src/main/java/com/tarbonicar/backend/api/comment/entity/Comment.java
  src/main/java/com/tarbonicar/backend/api/comment/repository/CommentRepository.java
  src/main/java/com/tarbonicar/backend/api/comment/service/CommentService.java
  src/main/java/com/tarbonicar/backend/common/config/sescurity/SecurityConfig.java
  src/main/java/com/tarbonicar/backend/common/response/ErrorStatus.java
  src/main/java/com/tarbonicar/backend/common/response/SuccessStatus.java
Labels: FEAT

#33 [FEAT] 내가 작성한 게시글 목록 조회 및 JWT 인증 연동
  src/main/java/com/tarbonicar/backend/api/article/controller/ArticleController.java
  src/main/java/com/tarbonicar/backend/api/article/repository/ArticleFilterRepository.java
  src/main/java/com/tarbonicar/backend/api/article/repository/ArticleFilterRepositoryImpl.java
  src/main/java/com/tarbonicar/backend/api/article/service/ArticleService.java
Labels: FEAT

#40 [REFAC] : Jwt 토큰 발급 방식 리팩토링
  build.gradle
  src/main/java/com/tarbonicar/backend/api/constant/Authority.java
  src/main/java/com/tarbonicar/backend/api/jwt/JwtFilter.java
  src/main/java/com/tarbonicar/backend/api/jwt/JwtProvider.java
  src/main/java/com/tarbonicar/backend/api/member/controller/MemberController.java
  src/main/java/com/tarbonicar/backend/api/member/dto/MemberLoginRequestDto.java
  src/main/java/com/tarbonicar/backend/api/member/dto/MemberLoginResponseDto.java
  src/main/java/com/tarbonicar/backend/api/member/entity/Member.java
  src/main/java/com/tarbonicar/backend/api/member/repository/MemberRepository.java
  src/main/java/com/tarbonicar/backend/api/member/service/MemberService.java
  src/main/java/com/tarbonicar/backend/common/config/sescurity/SecurityConfig.java
Labels: REFAC

#43 [FEAT] : 사용자 정보 조회 기능 구현
  src/main/java/com/tarbonicar/backend/api/member/controller/MemberController.java
  src/main/java/com/tarbonicar/backend/api/member/dto/MemberResponseDto.java
  src/main/java/com/tarbonicar/backend/api/member/service/MemberService.java
  src/main/java/com/tarbonicar/backend/common/response/ErrorStatus.java
Labels: FEAT

#39 [FEAT] 카카오 로그인 JWT 연동
  src/main/java/com/tarbonicar/backend/api/member/controller/MemberController.java
  src/main/java/com/tarbonicar/backend/api/member/service/MemberService.java
Labels: FEAT

#47 [FIX] 게시글 삭제 시 연관관계 데이터 삭제
  src/main/java/com/tarbonicar/backend/api/article/repository/ArticleLikeRepository.java
  src/main/java/com/tarbonicar/backend/api/article/service/ArticleService.java
  src/main/java/com/tarbonicar/backend/api/comment/repository/CommentRepository.java
Labels: FIX

#48 [FIX] 게시글 상세 조회 시 차종 필드 반환 추가
  src/main/java/com/tarbonicar/backend/api/article/dto/ArticleDetailResponseDTO.java
  src/main/java/com/tarbonicar/backend/api/article/service/ArticleService.java
Labels: FIX

#55 [FEAT] 댓글 페이지네이션 구현
  src/main/java/com/tarbonicar/backend/api/comment/controller/CommentController.java
  src/main/java/com/tarbonicar/backend/api/comment/repository/CommentRepository.java
  src/main/java/com/tarbonicar/backend/api/comment/service/CommentService.java
Labels: FEAT

#68 [FEAT] 비밀번호 찾기 이메일 발송, 인증 로직 구현
  build.gradle
  src/main/java/com/tarbonicar/backend/api/member/entity/Member.java
  src/main/java/com/tarbonicar/backend/api/passwordReset/controller/PasswordResetController.java
  src/main/java/com/tarbonicar/backend/api/passwordReset/dto/PasswordResetConfirmDTO.java
  src/main/java/com/tarbonicar/backend/api/passwordReset/dto/PasswordResetDTO.java
  src/main/java/com/tarbonicar/backend/api/passwordReset/dto/PasswordResetRequestDTO.java
  src/main/java/com/tarbonicar/backend/api/passwordReset/entity/PasswordReset.java
  src/main/java/com/tarbonicar/backend/api/passwordReset/repository/PasswordResetRepository.java
  src/main/java/com/tarbonicar/backend/api/passwordReset/service/PasswordResetService.java
  src/main/java/com/tarbonicar/backend/common/config/mail/MailConfig.java
  src/main/java/com/tarbonicar/backend/common/config/sescurity/SecurityConfig.java
  src/main/java/com/tarbonicar/backend/common/response/ErrorStatus.java
  src/main/java/com/tarbonicar/backend/common/response/SuccessStatus.java
Labels: FEAT

#72 [FEAT] 마이페이지 회원정보 수정, 내가 작성한 글
  src/main/java/com/tarbonicar/backend/api/article/controller/ArticleController.java
  src/main/java/com/tarbonicar/backend/api/article/repository/ArticleRepository.java
  src/main/java/com/tarbonicar/backend/api/article/service/ArticleService.java
  src/main/java/com/tarbonicar/backend/api/member/controller/MemberController.java
  src/main/java/com/tarbonicar/backend/api/member/dto/NicknameUpdateRequestDto.java
  src/main/java/com/tarbonicar/backend/api/member/dto/PasswordUpdateRequestDto.java
  src/main/java/com/tarbonicar/backend/api/member/entity/Member.java
  src/main/java/com/tarbonicar/backend/api/member/service/MemberService.java
  src/main/java/com/tarbonicar/backend/common/config/sescurity/SecurityConfig.java
  src/main/java/com/tarbonicar/backend/common/response/ErrorStatus.java
  src/main/java/com/tarbonicar/backend/common/response/SuccessStatus.java
  src/main/java/com/tarbonicar/backend/config/WebConfig.java
Labels: FEAT
